### ISSUE TITLE
Code Error Out Due to Shape Misalignment Between rgb and image

### ISSUE THREAD

**Issue by lilyzhng** [carlinds/unisim#1]
The code errored out at step 2490, at this line of code https://github.com/carlinds/unisim/blob/09b1df90f837a49f255198f81687490438a0c0cf/unisim/unisim.py#L786

I checked rgb shape changed from [4096, 3, 3, 3] to [4, 96, 96, 3] at step 2490. Can anyone explain why there would be a shape change here, and how to handle this bug?

```
Traceback (most recent call last):
File "nerfstudio/scripts/train.py", line 278, in
entrypoint()
File "nerfstudio/scripts/train.py", line 269, in entrypoint
main(
File "nerfstudio/scripts/train.py", line 254, in main
launch(
File "nerfstudio/scripts/train.py", line 196, in launch
main_func(local_rank=0, world_size=world_size, config=config)
File "nerfstudio/scripts/train.py", line 107, in train_loop
trainer.train()
File "/neurad-studio/nerfstudio/engine/trainer.py", line 316, in train
loss, loss_dict, metrics_dict = self.train_iteration(step)
File "/neurad-studio/nerfstudio/utils/profiler.py", line 112, in inner
out = func(*args, **kwargs)
File "/neurad-studio/nerfstudio/engine/trainer.py", line 555, in train_iteration
_, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
File "/neurad-studio/nerfstudio/utils/profiler.py", line 112, in inner
out = func(*args, **kwargs)
File "/neurad/lib/python3.8/site-packages/unisim/unisim_pipeline.py", line 75, in get_train_loss_dict
metrics_dict = self.model.get_metrics_dict(model_outputs, batch)
File "/neurad/lib/python3.8/site-packages/unisim/unisim.py", line 786, in get_metrics_dict
metrics_dict["psnr"] = self.psnr(rgb.detach(), image)
File "/neurad/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/neurad/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
File "/neurad/lib/python3.8/site-packages/torchmetrics/metric.py", line 311, in forward
self._forward_cache = self._forward_reduce_state_update(*args, **kwargs)
File "/neurad/lib/python3.8/site-packages/torchmetrics/metric.py", line 380, in _forward_reduce_state_update
self.update(*args, **kwargs)
File "/neurad/lib/python3.8/site-packages/torchmetrics/metric.py", line 492, in wrapped_func
raise err
File "/neurad/lib/python3.8/site-packages/torchmetrics/metric.py", line 482, in wrapped_func
update(*args, **kwargs)
File "/neurad/lib/python3.8/site-packages/torchmetrics/image/psnr.py", line 132, in update
sum_squared_error, num_obs = _psnr_update(preds, target, dim=self.dim)
File "/neurad/lib/python3.8/site-packages/torchmetrics/functional/image/psnr.py", line 73, in _psnr_update
sum_squared_error = torch.sum(torch.pow(preds - target, 2))
RuntimeError: The size of tensor a (96) must match the size of tensor b (3) at non-singleton dimension 2
```

**Comment by lilyzhng** [comment]
@atonderski Hi Adam, could you help verify what's wrong with the code? I tried it with both pandaset and kitti, both errored out. Thanks in advance.

**Comment by carlinds** [comment]
Hi @alchemz! We will have a look at this issue as soon as we can. Unfortunately, we are currently away on a conference and have limited time this week.

**Comment by lilyzhng** [comment]
@carlinds Thanks for the reply. I did some debugging, and found that
1. why it errored at step 2490:  it is because steps_per_stage = (2500, 7500, 10001), it is in fact errored out at the phase 1.
2. at phase 0, both image from batch, and rgb from model_outputs have the same shape, [4096, 3, 3, 3].
3. start from phase 1, the rgb from model_outputs got a new shape [4, 96, 96, 3], but image still have the same shape [4096, 3, 3, 3]. This is the cause of shape misalignment error `The size of tensor a (96) must match the size of tensor b (3) at non-singleton dimension 2`

To fix this shape misalignment, I wonder if we can at ln 85, do the rgb.permute(0, 3, 1, 2) from [4, 96, 96, 3] -->  [4, 3, 96, 96] in batch, channel, w, h. Then downsample 96x96 to 3x3? 
https://github.com/carlinds/unisim/blob/09b1df90f837a49f255198f81687490438a0c0cf/unisim/unisim_pipeline.py#L84-L86

**Comment by lilyzhng** [comment]
No worries. I figured it out how to fix it. Now it can train successfully beyond phase 0.

When self.phrase > 0, I reshaped the image tensor to be B x D x D x C, [4, 96, 96, 3] , 
`image = image.view(-1, *phase1_patch_size, image.shape[-1])`

**Comment by carlinds** [comment]
Hi. I have now looked into your issue. Did you perhaps run with `--pipeline.datamanager.num_processes=0`? I noticed a bug in the datamanager upstream where the change of patch sampler wasn't implemented for the case when we're not using multiprocessing. I have fixed this now (see https://github.com/georghess/neurad-studio/commit/073e06a9f70332480d6471f3c34aa2a80ad9d1e6), so please install the latest version of neurad-studio and have another try.

I do not recommend your proposed fix as it will not sample the image patches correctly.
